package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type versionJSON struct {
	Version          int32  `json:"version"`
	MinecraftVersion string `json:"minecraftVersion"`
	MajorVersion     string `json:"majorVersion"`
	ReleaseType      string `json:"releaseType"`
}

type protocolVersionJSON struct {
	MinecraftVersion string `json:"minecraftVersion"`
	Version          int32  `json:"version"`
	ReleaseType      string `json:"releaseType"`
}

type generatedVersion struct {
	MinecraftVersion string
	Protocol         int32
	MajorVersion     string
	ReleaseType      string
	HasProtocol      bool
	HasLoginPacket   bool
}

func main() {
	var pcDataDir string
	var outPath string
	flag.StringVar(&pcDataDir, "pc-data", "", "path to minecraft-data/data/pc")
	flag.StringVar(&outPath, "out", "", "output Go file")
	flag.Parse()

	if pcDataDir == "" || outPath == "" {
		fatalf("-pc-data and -out are required")
	}

	versions, err := readVersions(pcDataDir)
	if err != nil {
		fatalf("%v", err)
	}
	source, err := render(versions)
	if err != nil {
		fatalf("%v", err)
	}
	if err := os.WriteFile(outPath, source, 0o644); err != nil {
		fatalf("write %s: %v", outPath, err)
	}
}

func readVersions(pcDataDir string) ([]generatedVersion, error) {
	orderPath := filepath.Join(pcDataDir, "common", "versions.json")
	data, err := os.ReadFile(orderPath)
	if err != nil {
		return nil, fmt.Errorf("read version order: %w", err)
	}

	var orderedDirs []string
	if err := json.Unmarshal(data, &orderedDirs); err != nil {
		return nil, fmt.Errorf("parse version order: %w", err)
	}

	releaseTypes, err := readReleaseTypes(pcDataDir)
	if err != nil {
		return nil, err
	}

	versions := make([]generatedVersion, 0, len(orderedDirs))
	seen := make(map[string]struct{})
	for _, dir := range orderedDirs {
		versionPath := filepath.Join(pcDataDir, dir, "version.json")
		if _, err := os.Stat(versionPath); err != nil {
			continue
		}
		version, err := readVersion(versionPath)
		if err != nil {
			return nil, err
		}
		if version.Version <= 0 || version.MinecraftVersion == "" {
			continue
		}
		version.ReleaseType = releaseTypeFor(version, releaseTypes)
		if version.ReleaseType != "release" || !isModernJava(version.MajorVersion) || !isReleaseName(version.MinecraftVersion) {
			continue
		}
		key := version.MinecraftVersion + "/" + strconv.Itoa(int(version.Version))
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}

		versions = append(versions, generatedVersion{
			MinecraftVersion: version.MinecraftVersion,
			Protocol:         version.Version,
			MajorVersion:     version.MajorVersion,
			ReleaseType:      version.ReleaseType,
			HasProtocol:      fileExists(filepath.Join(pcDataDir, dir, "protocol.json")),
			HasLoginPacket:   fileExists(filepath.Join(pcDataDir, dir, "loginPacket.json")),
		})
	}
	if len(versions) == 0 {
		return nil, fmt.Errorf("no versions found in %s", pcDataDir)
	}
	return versions, nil
}

func readReleaseTypes(pcDataDir string) (map[string]string, error) {
	path := filepath.Join(pcDataDir, "common", "protocolVersions.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read protocol versions: %w", err)
	}
	var entries []protocolVersionJSON
	if err := json.Unmarshal(data, &entries); err != nil {
		return nil, fmt.Errorf("parse protocol versions: %w", err)
	}

	releaseTypes := make(map[string]string, len(entries)*2)
	for _, entry := range entries {
		releaseType := releaseType(entry.ReleaseType)
		releaseTypes[entry.MinecraftVersion] = releaseType
		releaseTypes[entry.MinecraftVersion+"/"+strconv.Itoa(int(entry.Version))] = releaseType
	}
	return releaseTypes, nil
}

func readVersion(path string) (versionJSON, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return versionJSON{}, fmt.Errorf("read %s: %w", path, err)
	}
	var version versionJSON
	if err := json.Unmarshal(data, &version); err != nil {
		return versionJSON{}, fmt.Errorf("parse %s: %w", path, err)
	}
	return version, nil
}

func render(versions []generatedVersion) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/mcdata-gen; DO NOT EDIT.\n")
	buf.WriteString("package versions\n\n")
	buf.WriteString("var allVersions = []Version{\n")
	for _, version := range versions {
		fmt.Fprintf(&buf, "\t{MinecraftVersion: %q, Protocol: %d, MajorVersion: %q, ReleaseType: %q, HasProtocol: %t, HasLoginPacket: %t},\n",
			version.MinecraftVersion,
			version.Protocol,
			version.MajorVersion,
			version.ReleaseType,
			version.HasProtocol,
			version.HasLoginPacket,
		)
	}
	buf.WriteString("}\n\n")
	buf.WriteString("var byProtocol = map[int32][]Version{\n")
	lastProtocol := int32(-1)
	for _, version := range versions {
		if version.Protocol == lastProtocol {
			continue
		}
		lastProtocol = version.Protocol
		fmt.Fprintf(&buf, "\t%d: {", version.Protocol)
		for _, candidate := range versions {
			if candidate.Protocol != version.Protocol {
				continue
			}
			fmt.Fprintf(&buf, "{MinecraftVersion: %q, Protocol: %d, MajorVersion: %q, ReleaseType: %q, HasProtocol: %t, HasLoginPacket: %t},",
				candidate.MinecraftVersion,
				candidate.Protocol,
				candidate.MajorVersion,
				candidate.ReleaseType,
				candidate.HasProtocol,
				candidate.HasLoginPacket,
			)
		}
		buf.WriteString("},\n")
	}
	buf.WriteString("}\n")

	source, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, buf.String())
	}
	return source, nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func releaseType(value string) string {
	if value == "" {
		return "release"
	}
	return strings.ToLower(value)
}

func releaseTypeFor(version versionJSON, releaseTypes map[string]string) string {
	if releaseType, ok := releaseTypes[version.MinecraftVersion+"/"+strconv.Itoa(int(version.Version))]; ok {
		return releaseType
	}
	if releaseType, ok := releaseTypes[version.MinecraftVersion]; ok {
		return releaseType
	}
	return releaseType(version.ReleaseType)
}

func isModernJava(majorVersion string) bool {
	return strings.HasPrefix(majorVersion, "1.") || strings.HasPrefix(majorVersion, "26.")
}

func isReleaseName(minecraftVersion string) bool {
	if strings.Contains(minecraftVersion, "-pre") || strings.Contains(minecraftVersion, "-rc") {
		return false
	}
	for _, part := range strings.Split(minecraftVersion, ".") {
		if strings.Contains(part, "w") {
			return false
		}
	}
	return true
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, "mcdata-gen: "+format+"\n", args...)
	os.Exit(1)
}
