package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type versionJSON struct {
	Version          int32  `json:"version"`
	MinecraftVersion string `json:"minecraftVersion"`
	MajorVersion     string `json:"majorVersion"`
	ReleaseType      string `json:"releaseType"`
}

type protocolVersionJSON struct {
	MinecraftVersion string `json:"minecraftVersion"`
	Version          int32  `json:"version"`
	ReleaseType      string `json:"releaseType"`
}

type blockJSON struct {
	ID           int32   `json:"id"`
	Name         string  `json:"name"`
	DefaultState *uint32 `json:"defaultState"`
}

type protocolBlocks struct {
	Protocol int32
	Blocks   map[string]uint32
}

func main() {
	var pcDataDir string
	var outPath string
	flag.StringVar(&pcDataDir, "pc-data", "", "path to minecraft-data/data/pc")
	flag.StringVar(&outPath, "out", "", "output Go file")
	flag.Parse()

	if pcDataDir == "" || outPath == "" {
		fatalf("-pc-data and -out are required")
	}
	blocks, err := readProtocolBlocks(pcDataDir)
	if err != nil {
		fatalf("%v", err)
	}
	source, err := render(blocks)
	if err != nil {
		fatalf("%v", err)
	}
	if err := os.WriteFile(outPath, source, 0o644); err != nil {
		fatalf("write %s: %v", outPath, err)
	}
}

func readProtocolBlocks(pcDataDir string) ([]protocolBlocks, error) {
	orderPath := filepath.Join(pcDataDir, "common", "versions.json")
	data, err := os.ReadFile(orderPath)
	if err != nil {
		return nil, fmt.Errorf("read version order: %w", err)
	}
	var orderedDirs []string
	if err := json.Unmarshal(data, &orderedDirs); err != nil {
		return nil, fmt.Errorf("parse version order: %w", err)
	}
	releaseTypes, err := readReleaseTypes(pcDataDir)
	if err != nil {
		return nil, err
	}

	byProtocol := map[int32]protocolBlocks{}
	var latestBlocks map[string]uint32
	for _, dir := range orderedDirs {
		version, err := readVersion(filepath.Join(pcDataDir, dir, "version.json"))
		if err != nil || version.Version <= 0 || version.MinecraftVersion == "" {
			continue
		}
		version.ReleaseType = releaseTypeFor(version, releaseTypes)
		if version.ReleaseType != "release" || !isModernJava(version.MajorVersion) || !isReleaseName(version.MinecraftVersion) {
			continue
		}
		if blocks, err := readBlocks(filepath.Join(pcDataDir, dir, "blocks.json")); err == nil {
			latestBlocks = blocks
		}
		if latestBlocks == nil {
			continue
		}
		byProtocol[version.Version] = protocolBlocks{
			Protocol: version.Version,
			Blocks:   latestBlocks,
		}
	}

	out := make([]protocolBlocks, 0, len(byProtocol))
	for _, blocks := range byProtocol {
		out = append(out, blocks)
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].Protocol < out[j].Protocol
	})
	if len(out) == 0 {
		return nil, fmt.Errorf("no block states found in %s", pcDataDir)
	}
	return out, nil
}

func readVersion(path string) (versionJSON, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return versionJSON{}, err
	}
	var version versionJSON
	if err := json.Unmarshal(data, &version); err != nil {
		return versionJSON{}, err
	}
	return version, nil
}

func readBlocks(path string) (map[string]uint32, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var raw []blockJSON
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	blocks := make(map[string]uint32, len(raw))
	for _, block := range raw {
		if block.Name == "" || block.ID < 0 {
			continue
		}
		state := uint32(block.ID) << 4
		if block.DefaultState != nil {
			state = *block.DefaultState
		}
		blocks[block.Name] = state
	}
	return blocks, nil
}

func readReleaseTypes(pcDataDir string) (map[string]string, error) {
	path := filepath.Join(pcDataDir, "common", "protocolVersions.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read protocol versions: %w", err)
	}
	var entries []protocolVersionJSON
	if err := json.Unmarshal(data, &entries); err != nil {
		return nil, fmt.Errorf("parse protocol versions: %w", err)
	}
	releaseTypes := make(map[string]string, len(entries)*2)
	for _, entry := range entries {
		releaseType := releaseType(entry.ReleaseType)
		releaseTypes[entry.MinecraftVersion] = releaseType
		releaseTypes[entry.MinecraftVersion+"/"+strconv.Itoa(int(entry.Version))] = releaseType
	}
	return releaseTypes, nil
}

func render(protocols []protocolBlocks) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/mcblockstate-gen; DO NOT EDIT.\n")
	buf.WriteString("package blockstate\n\n")
	buf.WriteString("var byProtocol = map[int32]map[string]uint32{\n")
	for _, protocol := range protocols {
		fmt.Fprintf(&buf, "\t%d: {\n", protocol.Protocol)
		names := make([]string, 0, len(protocol.Blocks))
		for name := range protocol.Blocks {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			fmt.Fprintf(&buf, "\t\t%q: %d,\n", name, protocol.Blocks[name])
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
	source, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return source, nil
}

func releaseType(value string) string {
	if value == "" {
		return "release"
	}
	return strings.ToLower(value)
}

func releaseTypeFor(version versionJSON, releaseTypes map[string]string) string {
	if releaseType, ok := releaseTypes[version.MinecraftVersion+"/"+strconv.Itoa(int(version.Version))]; ok {
		return releaseType
	}
	if releaseType, ok := releaseTypes[version.MinecraftVersion]; ok {
		return releaseType
	}
	return releaseType(version.ReleaseType)
}

func isModernJava(majorVersion string) bool {
	return strings.HasPrefix(majorVersion, "1.") || strings.HasPrefix(majorVersion, "26.")
}

func isReleaseName(minecraftVersion string) bool {
	if strings.Contains(minecraftVersion, "-pre") || strings.Contains(minecraftVersion, "-rc") {
		return false
	}
	for _, part := range strings.Split(minecraftVersion, ".") {
		if strings.Contains(part, "w") {
			return false
		}
	}
	return true
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, "mcblockstate-gen: "+format+"\n", args...)
	os.Exit(1)
}
