package packetid

func init() {
	byProtocol[775] = VersionPackets{
		MinecraftVersion: "26.1.2",
		Protocol:         775,
		Entries: []Entry{
			{State: StateLogin, Direction: ToClient, Name: "disconnect", ID: 0},
			{State: StateLogin, Direction: ToClient, Name: "encryption_begin", ID: 1},
			{State: StateLogin, Direction: ToClient, Name: "success", ID: 2},
			{State: StateLogin, Direction: ToClient, Name: "compress", ID: 3},
			{State: StateLogin, Direction: ToClient, Name: "login_plugin_request", ID: 4},
			{State: StateLogin, Direction: ToClient, Name: "cookie_request", ID: 5},
			{State: StateLogin, Direction: ToServer, Name: "login_start", ID: 0},
			{State: StateLogin, Direction: ToServer, Name: "encryption_begin", ID: 1},
			{State: StateLogin, Direction: ToServer, Name: "login_plugin_response", ID: 2},
			{State: StateLogin, Direction: ToServer, Name: "login_acknowledged", ID: 3},
			{State: StateLogin, Direction: ToServer, Name: "cookie_response", ID: 4},

			{State: StateConfiguration, Direction: ToClient, Name: "cookie_request", ID: 0},
			{State: StateConfiguration, Direction: ToClient, Name: "custom_payload", ID: 1},
			{State: StateConfiguration, Direction: ToClient, Name: "disconnect", ID: 2},
			{State: StateConfiguration, Direction: ToClient, Name: "finish_configuration", ID: 3},
			{State: StateConfiguration, Direction: ToClient, Name: "keep_alive", ID: 4},
			{State: StateConfiguration, Direction: ToClient, Name: "ping", ID: 5},
			{State: StateConfiguration, Direction: ToClient, Name: "reset_chat", ID: 6},
			{State: StateConfiguration, Direction: ToClient, Name: "registry_data", ID: 7},
			{State: StateConfiguration, Direction: ToClient, Name: "remove_resource_pack", ID: 8},
			{State: StateConfiguration, Direction: ToClient, Name: "add_resource_pack", ID: 9},
			{State: StateConfiguration, Direction: ToClient, Name: "store_cookie", ID: 10},
			{State: StateConfiguration, Direction: ToClient, Name: "transfer", ID: 11},
			{State: StateConfiguration, Direction: ToClient, Name: "feature_flags", ID: 12},
			{State: StateConfiguration, Direction: ToClient, Name: "tags", ID: 13},
			{State: StateConfiguration, Direction: ToClient, Name: "select_known_packs", ID: 14},
			{State: StateConfiguration, Direction: ToClient, Name: "custom_report_details", ID: 15},
			{State: StateConfiguration, Direction: ToClient, Name: "server_links", ID: 16},
			{State: StateConfiguration, Direction: ToClient, Name: "clear_dialog", ID: 17},
			{State: StateConfiguration, Direction: ToClient, Name: "show_dialog", ID: 18},
			{State: StateConfiguration, Direction: ToClient, Name: "code_of_conduct", ID: 19},
			{State: StateConfiguration, Direction: ToServer, Name: "settings", ID: 0},
			{State: StateConfiguration, Direction: ToServer, Name: "cookie_response", ID: 1},
			{State: StateConfiguration, Direction: ToServer, Name: "custom_payload", ID: 2},
			{State: StateConfiguration, Direction: ToServer, Name: "finish_configuration", ID: 3},
			{State: StateConfiguration, Direction: ToServer, Name: "keep_alive", ID: 4},
			{State: StateConfiguration, Direction: ToServer, Name: "pong", ID: 5},
			{State: StateConfiguration, Direction: ToServer, Name: "resource_pack_receive", ID: 6},
			{State: StateConfiguration, Direction: ToServer, Name: "select_known_packs", ID: 7},
			{State: StateConfiguration, Direction: ToServer, Name: "custom_click_action", ID: 8},
			{State: StateConfiguration, Direction: ToServer, Name: "accept_code_of_conduct", ID: 9},

			{State: StatePlay, Direction: ToClient, Name: "difficulty", ID: 10},
			{State: StatePlay, Direction: ToClient, Name: "chunk_batch_finished", ID: 11},
			{State: StatePlay, Direction: ToClient, Name: "chunk_batch_start", ID: 12},
			{State: StatePlay, Direction: ToClient, Name: "clear_titles", ID: 14},
			{State: StatePlay, Direction: ToClient, Name: "custom_payload", ID: 24},
			{State: StatePlay, Direction: ToClient, Name: "kick_disconnect", ID: 32},
			{State: StatePlay, Direction: ToClient, Name: "keep_alive", ID: 44},
			{State: StatePlay, Direction: ToClient, Name: "map_chunk", ID: 45},
			{State: StatePlay, Direction: ToClient, Name: "update_light", ID: 48},
			{State: StatePlay, Direction: ToClient, Name: "login", ID: 49},
			{State: StatePlay, Direction: ToClient, Name: "position", ID: 72},
			{State: StatePlay, Direction: ToClient, Name: "remove_resource_pack", ID: 80},
			{State: StatePlay, Direction: ToClient, Name: "add_resource_pack", ID: 81},
			{State: StatePlay, Direction: ToClient, Name: "action_bar", ID: 87},
			{State: StatePlay, Direction: ToClient, Name: "update_view_position", ID: 94},
			{State: StatePlay, Direction: ToClient, Name: "update_view_distance", ID: 95},
			{State: StatePlay, Direction: ToClient, Name: "simulation_distance", ID: 111},
			{State: StatePlay, Direction: ToClient, Name: "set_title_subtitle", ID: 112},
			{State: StatePlay, Direction: ToClient, Name: "update_time", ID: 113},
			{State: StatePlay, Direction: ToClient, Name: "set_title_text", ID: 114},
			{State: StatePlay, Direction: ToClient, Name: "set_title_time", ID: 115},
			{State: StatePlay, Direction: ToClient, Name: "store_cookie", ID: 120},
			{State: StatePlay, Direction: ToClient, Name: "system_chat", ID: 121},
			{State: StatePlay, Direction: ToClient, Name: "transfer", ID: 129},
			{State: StatePlay, Direction: ToClient, Name: "clear_dialog", ID: 139},
			{State: StatePlay, Direction: ToClient, Name: "show_dialog", ID: 140},
			{State: StatePlay, Direction: ToServer, Name: "chat_command", ID: 7},
			{State: StatePlay, Direction: ToServer, Name: "chat_message", ID: 9},
			{State: StatePlay, Direction: ToServer, Name: "chunk_batch_received", ID: 11},
			{State: StatePlay, Direction: ToServer, Name: "configuration_acknowledged", ID: 16},
			{State: StatePlay, Direction: ToServer, Name: "cookie_response", ID: 21},
			{State: StatePlay, Direction: ToServer, Name: "custom_payload", ID: 22},
			{State: StatePlay, Direction: ToServer, Name: "keep_alive", ID: 28},
			{State: StatePlay, Direction: ToServer, Name: "resource_pack_receive", ID: 49},
			{State: StatePlay, Direction: ToServer, Name: "custom_click_action", ID: 68},
		},
	}
}
